config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: "articles#index"
    
    resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article has been created"
      redirect_to articles_path
    else
       flash.now[:danger] = "Article has not been created"
       render :new
    end
  end
  
  private
  
  def article_params
    params.require(:article).permit(:title, :body)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h3 class="text-center">Adding New Article</h3>

<div class="row">
    <div class="col-md-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <% if @article.errors.any? %>
        <div class="panel panel-danger col-md-offset-1">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <%= pluralize(@article.errors.count, "error") %>
                    prohibited this article from being saved:
                </h2>
                
                <div class="panel-body">
                   <ul>
                      <% @article.errors.full_messages.each do |msg| %>
                          <li>
                              <%= msg %>
                          </li>
                      <% end %>
                  </ul>
                </div>
            </div>
        </div>
        <% end %>
            <div class="form-group">
                <div class="control-label col-md-1">
                    <%= f.label :title %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :title, class: 'form-control', placeholder: "Title of article", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-1">
                    <%= f.label :body %>
                </div>
                <div class="col-md-8">
                    <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Body of article' %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-1 col-md-11">
                    <%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Estore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header role="banner">
      <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Blog App", root_path, class: "navbar-brand" %>
    </div>  
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Authors", "#" %></li>
      </ul>
    </div>
  </div>
</nav>
    </header>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |key, message| %>
            <div class="text-center alert alert-<%= key == 'notice'? 'success': 'danger' %>">
              <%= message %>
            </div> 
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>